# Generated by Django 2.0.3 on 2018-03-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_stock', models.BooleanField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'small'), (2, 'medium'), (3, 'large')], null=True)),
            ],
        ),
    ]
